### ISSUE TITLE
Cant harvest custom tables that worked 3 weeks ago.

### ISSUE THREAD

**Issue by Asiermd** [OhhLoz/Harvester#43] opened 2024-04-10 18:41 UTC
Module Version: v1.8.0

Describe the bug
Constant message about no resource being able to be drawn

To Reproduce

Try to use previously working custom tables
See error
Expected behavior
For the tables to work as previously did

Screenshots
![image](https://github.com/OhhLoz/Harvester/assets/45450286/7b3b44c4-9739-40af-a8a7-7173b6159d56)

Browser:
Google Chrome Versión 122.0.6261.70 (Build oficial) (64 bits)

Foundry Version:

Version 11 Build 315

Game System:

DnD 5e

**Comment by p4535992** [comment] 2024-04-10 19:20
If you click on the "Roll +" button is working ? (sound like a BRT problem)

**Comment by Asiermd** [comment] 2024-04-10 19:32
Yes, it does work.
strangely enough, even normal tables have the message, i have tried with an aaracokra, an adult gree ndragon and a giant spider, and it doesnt let me harvest them. My default sheet for tables is the harvest table if that information helps in anything.

**Comment by p4535992** [comment] 2024-04-10 20:03
Can you check out the uuid (click f12 search for the yellow message, the first argument is the rolltable object), i think there is another table with the "Arctic" on the wolrd ?

That error usually mean the table is not normalized ? Try to click on the "Balance" icon  or this macro

```
const tableUuid = <UUID OF THE TABLE>;
const table = await fromUuid(tableUuid);
	await table.update({
		results: table.results.map(result => ({
			_id: result.id, weight: result.range[1] - (result.range[0] - 1)
		}))
	});
	await table.normalize();		
```

**Comment by Asiermd** [comment] 2024-04-10 20:29
Here are the warning messages:
![image](https://github.com/OhhLoz/Harvester/assets/45450286/b346808f-d277-4c06-902f-77f5e38423ff)

The two tables i use, i want for the first to roll  on the second table a number of times depending on how well the characters  do their own survival rolls, and i think there is nothing wrong with them, they worked before.
![image](https://github.com/OhhLoz/Harvester/assets/45450286/cd1db0d3-a37d-46e5-9c0f-70fa83a12366)

**Comment by p4535992** [comment] 2024-04-10 20:43
Nothing.. seem all right the last thing i can do is try to replicate the issue on my local macine... can you export these twiorolltable (as json then rename with .txt for github stupid rule) and pass to me ?
Sorry about this i make many test, but i must have miss something...

**Comment by ctbritt** [comment] 2024-04-10 22:32
having the same issue. I wonder if the issue is two harvester compendia of roll tables
1. harvester.harvester from the Harvester Module
2. BRT harvester rolltable from BRT. better-rolltables.brt-harvest-harvester

I have both and can't get rid of the BRT tables, since it's part of the BRT module, and I need that to make Harvester work.

**Comment by p4535992** [comment] 2024-04-11 07:04
It shouldn't be **if the BRT is activate there is a priority order** https://github.com/OhhLoz/Harvester/blob/06d544171e962fc3ca59f045f2ea91bf8919f3c0/src/scripts/lib/better-rolltables-helpers.js#L61 after this i just get the first rolltables of the array so there is no collision

**Comment by Asiermd** [comment] 2024-04-11 12:51
Here are both the first and second artic tables

[fvtt-RollTable-arctic-ooRVP3bNhg0LLHG1.txt](https://github.com/OhhLoz/Harvester/files/14946324/fvtt-RollTable-arctic-ooRVP3bNhg0LLHG1.txt)
[fvtt-RollTable-gathering_-arctic-n1Sd7x4uzjlxglRm.txt](https://github.com/OhhLoz/Harvester/files/14946325/fvtt-RollTable-gathering_-arctic-n1Sd7x4uzjlxglRm.txt)

**Comment by Asiermd** [comment] 2024-04-11 12:56
And another screenshot of the warnings, now about an air elemental, as if trying to see if some or any monster at all could work:
![image](https://github.com/OhhLoz/Harvester/assets/45450286/a2a8c6a7-9076-4a44-9126-050430e1c1ab)
and the game settings screenshot, if it helps with something:
![image](https://github.com/OhhLoz/Harvester/assets/45450286/53b0eaab-9778-443d-b4bc-9b5ad71490b4)
![image](https://github.com/OhhLoz/Harvester/assets/45450286/2d32e896-d277-4746-b2a6-b45988f30ab8)

**Comment by p4535992** [comment] 2024-04-11 18:31
i think the bug was on brt side try out the new combination
- Harvester 1.8.2
- BRT: 2.1.14

**Comment by Asiermd** [comment] 2024-04-11 19:47
I have updated both tables and the error is still there.
Tried with a prewritten monster, and the error still there.

**Comment by ctbritt** [comment] 2024-04-11 20:54
Yeah. updated as well. Really not sure what is going on. 

Here's a screenshot of the latest: https://share.cleanshot.com/bfXH8c4D

**Comment by p4535992** [comment] 2024-04-11 21:11
Did you click on the update button ?

**Comment by ctbritt** [comment] 2024-04-11 21:11
Yes

**Comment by p4535992** [comment] 2024-04-11 21:18
Are you sure you donìt have any red lock active on the roltable ? 
![Uploading 2024-04-11 23 17 47.png…]()

**Comment by p4535992** [comment] 2024-04-11 21:18
Are you sure you don't have any red lock active on the rolltable ?
![2024-04-11 23 17 47](https://github.com/OhhLoz/Harvester/assets/5201916/2bf90c02-69b5-4202-82ca-8f3ea68eabc4)

**Comment by ctbritt** [comment] 2024-04-11 21:19
![CleanShot 2024-04-11 at 17 19 44](https://github.com/OhhLoz/Harvester/assets/4516034/7d8ce390-a5ac-4403-8f18-bd5ddc45d9e8)

**Comment by p4535992** [comment] 2024-04-11 21:24
Can'r replicate uninstall and reinstall the module ? working fine on my side tested an retested.
![2024-04-11 23 24 07](https://github.com/OhhLoz/Harvester/assets/5201916/397a9de9-a3b3-42ae-a67d-214e09fbdd2b)

**Comment by p4535992** [comment] 2024-04-11 21:26
If you use BRT you must check the other compendium and the rolltable **Better Harvester | Hill Giant RollTable**

**Comment by ctbritt** [comment] 2024-04-11 21:34
I've checked both tables. neither have any red in them. I've both Harvest | Hill Giant and Better Harvester | Hill Giant tables to my world, no red. There is no red in the compendia either.

**Comment by p4535992** [comment] 2024-04-11 21:41
can i acces your world ? and made a test ?

**Comment by ctbritt** [comment] 2024-04-11 21:49
yes, find me on discord and I'll send you login info. thanks very much!

**Comment by p4535992** [comment] 2024-04-11 22:24
k i discovered the issue it was my fault.... i should be able to solve this tomorrow, orry again for this

**Comment by p4535992** [comment] 2024-04-12 17:28
possible resolved with version 1.8.3.... let me know it.

**Comment by Asiermd** [comment] 2024-04-12 17:35
I ahve just updated the world, at it seems to be working, will keep trying with all the custom harvests i have i will let you know

**Comment by Asiermd** [comment] 2024-04-12 17:46
Strangely enough, there are some official creatures that doesnt let me harvest them, for example the aartuk elder, the Giant Hyena and the air elemental, at least the few ones i have tried

**Comment by p4535992** [comment] 2024-04-12 18:36
Fixed not removed  on next release (because some people like a more manual way ???): _"Auto Assign to Players" MUST be enabled. it won't return any results otherwise. Suggest just removing this setting, since it seems like the default anyway._

Fixed on next release: _Can't seem to change the regex function to determine which table it gets data from_ (more test needed ???)

**Comment by p4535992** [comment] 2024-04-12 18:57
The last 2 bug from @ctbritt should be solved on 1.8.4, but the one from @Asiermd  not sure... maybe it was the bug on thefake regex ? can you try again ?

**Comment by Asiermd** [comment] 2024-04-12 19:50
Updated the module and keeps happening, not with all, but with some, i managed to harvest an otyugh but not a giant spider
![image](https://github.com/OhhLoz/Harvester/assets/45450286/84c05620-5227-47f6-9d7e-8d55256b9c03)
![image](https://github.com/OhhLoz/Harvester/assets/45450286/200a07eb-5086-4287-919c-84a33db8eaf5)

**Comment by p4535992** [comment] 2024-04-12 20:02
Can i access your world ? sadly i cannot replicate this on my side

**Comment by ctbritt** [comment] 2024-04-13 14:16
Seems to be working pretty well for me here! there are some edge cases that seem to want custom tables, like a homebrew Cave Dragon not being recognized. But overall, it's working well! thanks for all your hard work on this.

**Comment by p4535992** [comment] 2024-04-14 09:39
For finally close this issue on 1.8.5 i add for @Asiermd  a check for min dc (only with BRT) for avoid confusion between "I don't find any table" with "the rolled dc is just not enough"

There are two chat messages now:

'Afsr' **attempted** to harvest resources from 'Shadow Demon' but failed to find anything for this creature.

'Afsr' **try is best** to harvest resources from 'Shadow Demon' but failed to find anything for this creature.

and a explicit log on the web console:

The rolled dc 'XXX' is not enough for this table 'YYY' the minimal DC is 'ZZZ'

**Closed by p4535992** 2024-04-14 09:39 UTC
Labels: bug
